#!/bin/bash
#
# Exit immediately if a command exits with a non-zero status
set -e

# Helper function to print text and sleep for 3 seconds
run_step() {
    echo "=== $1 ==="
    sleep 3
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root or with sudo" >&2
    exit 1
fi

# The join command printed by ks8_install_master.sh (step 21) must be passed
# in as arguments, e.g.:
#   sudo ./ks8_install_worker.sh kubeadm join 10.0.0.5:6443 --token abcd.xyz \
#       --discovery-token-ca-cert-hash sha256:xxxx
if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <kubeadm join command from the master>" >&2
    echo "Example: $0 kubeadm join 1.2.3.4:6443 --token xxx --discovery-token-ca-cert-hash sha256:xxx" >&2
    exit 1
fi
JOIN_CMD="$*"

run_step "0. Changing docker script to Execute Mode"
if sudo chmod +x /home/pc/devops/docker/docker_install.sh
then 
  . /home/pc/devops/docker/docker_install.sh
else
    echo "Docker not Installed"
    exit 1
fi
echo ""

run_step "9. Disabling Swap (Required by Kubernetes)"
sudo swapoff -a
sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
echo ""


run_step "10. Installing Kubernetes "
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl
sudo systemctl enable --now kubelet
echo ""

run_step "11. Enable kernel modules"
sudo modprobe br_netfilter
echo ""

run_step "12. Add some settings to sysctl"
sudo sysctl -w net.ipv4.ip_forward=1
echo ""

run_step "14. Join the Kubernetes Cluster"
# NOTE: workers do NOT have /etc/kubernetes/admin.conf - that file is
# generated by 'kubeadm init' on the master only. Instead, the worker
# joins the cluster with the token/hash provided by the master.
eval "sudo $JOIN_CMD"
echo ""

run_step "15. Verify Installation"
echo "This node does not run kubectl against the cluster by default."
echo "To verify, run 'kubectl get nodes' on the master - this worker"
echo "should show up with STATUS 'Ready' shortly after joining."
echo ""

       echo "========================================================="
       echo " Installation Complete!"
       echo " This worker node has joined the cluster."
       echo " Verify with 'kubectl get nodes' on the master."
       echo "========================================================="

